export * from './auth.controller'
// export * from './call.controller'
// export * from './chat.controller'
// export * from './consults.controller'
// export * from './diagnostics.controller'
export * from './users.controller'
export * from './psychologist.controller'
export * from './patient.controller'